### ISSUE TITLE
Can I help you not need this?

### ISSUE THREAD

**Issue by jordansissel** [18F/cg-logstash-output-s3-backport-release#1]
I saw this on [twitter](https://twitter.com/newgovrepos/status/789642252356317184) and came to check it out.

I poked around, and I'm not sure what version of Logstash this is for, but  looking at the patch (and its [origin](https://github.com/logstash-plugins/logstash-output-s3/commit/13eb689a046dd5c6c78d8111d392ff67f5402b23)), it's pretty small! 

Would it help if I backported this patch for you to some verison of the s3 output plugin so you would'nt need this repo?

**Comment by cnelson** [comment]
@jordansissel Just saw this comment, and thanks for offering to help!

Yes, it'd be great to get this simple fix ported into the LS 2.x release as that's what the upstream bosh release is still on: https://github.com/logsearch/logsearch-boshrelease/blob/develop/packages/logstash/spec

It looks like from the discussion in the PR, other folks would like this in the 2.x releases as well: https://github.com/logstash-plugins/logstash-output-s3/issues/62#issuecomment-220303655

Let me know what's the best way to accomplish this, happy to help where I can!

**Comment by jordansissel** [comment]
I will do some research and get back to you.

**Comment by jordansissel** [comment]
Best I can tell, this works in the latest Logstash 2.x (2.4.x).

In Logstash 2.4.1 I am successful in using the latest version of the S3 output with no changes required other than installing it:

```
% bin/logstash --version 
logstash 2.4.1

% bin/logstash-plugin install --version 3.2.0 logstash-output-s3 
Validating logstash-output-s3-3.2.0
Installing logstash-output-s3
Installation successful
```

I used it to write to S3 with the following config:

```
output {
  s3 {
    access_key_id => "xxx"
    secret_access_key => "xxx"
    bucket => "xxx"
    prefix => "users/jordansissel/s3test/"
    server_side_encryption => true

    # Set time_file to 1 minute so it uploads quickly enough that I can see the result.
    time_file => 1
  }
}
```

When it uploaded to S3, I see this in AWS S3 console:
![image](https://cloud.githubusercontent.com/assets/131818/20408743/9922082c-accb-11e6-8eef-50cb51335d25.png)

**Comment by jordansissel** [comment]
As a side note, it works in Logstash 2.4 but not 2.3 or older because we backported many of the newer Plugin APIs from Logstash 5 into Logstash 2.4 to help ease the transition from Logstash 2.x to 5.x (as well as helping us, as authors, provide plugins that work on both 5.x and 2.4)

**Comment by cnelson** [comment]
Nice!  I'll see about bumping the versions in the bosh release.  Thanks so much for looking into this!
